/**
 * Pre-generates AI "Flavor Profile" data for EVERY dish across all venues and writes
 * a static map to src/data/flavorProfiles.ts. The app reads this map first (instant,
 * no runtime quota dependency); only dishes missing here fall back to a live call.
 *
 * Uses BOTH providers in parallel — a Gemini worker and a Claude (Sonnet 4.6) worker
 * pull from one shared queue, each paced to its own rate limit. Roughly halves wall
 * time and survives either provider hitting a cap. Claude is used only when
 * ANTHROPIC_API_KEY is present in .env; otherwise it's Gemini-only.
 *
 *   node scripts/generateFlavorProfiles.mjs --count   # list dishes, no API calls
 *   node scripts/generateFlavorProfiles.mjs           # generate (AR dishes first)
 */
import { build } from 'esbuild';
import { readFileSync, existsSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const VENUES = ['mayanagri', 'sesame', 'croft-house'];
const OUT = resolve(ROOT, 'src/data/flavorProfiles.ts');
const COUNT_ONLY = process.argv.includes('--count');

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// ---------- load TS venue data by bundling in-memory ----------
async function loadVenue(id) {
  const res = await build({
    entryPoints: [resolve(ROOT, `src/data/venues/${id}.ts`)],
    bundle: true, format: 'esm', write: false, platform: 'node', logLevel: 'silent',
  });
  const mod = await import('data:text/javascript,' + encodeURIComponent(res.outputFiles[0].text));
  return mod.data;
}

async function allDishes() {
  const dishes = [];
  for (const v of VENUES) {
    const cafe = await loadVenue(v);
    for (const d of cafe.menu || []) {
      dishes.push({ id: d.id, name: d.name, description: d.description || '', category: d.category || '', arEnabled: d.arEnabled === true });
    }
  }
  const seen = new Set();
  return dishes
    .filter((d) => (seen.has(d.id) ? false : seen.add(d.id)))
    .sort((a, b) => (b.arEnabled === a.arEnabled ? 0 : b.arEnabled ? 1 : -1));
}

// ---------- output file (resumable, incremental) ----------
function loadExisting() {
  if (!existsSync(OUT)) return {};
  try {
    const m = readFileSync(OUT, 'utf8').match(/export const flavorProfiles[^=]*=\s*(\{[\s\S]*\});?\s*$/);
    return m ? JSON.parse(m[1]) : {};
  } catch { return {}; }
}
function writeOut(map) {
  const header = `// AUTO-GENERATED by scripts/generateFlavorProfiles.mjs — do not edit by hand.\n` +
    `// AI flavor profiles baked at build time so every dish has an instant, quota-free profile.\n` +
    `export interface BakedFlavorNote { label: string; percentage: number; }\n` +
    `export interface BakedFlavorProfile { notes: BakedFlavorNote[]; tastingNote: string; }\n\n` +
    `export const flavorProfiles: Record<string, BakedFlavorProfile> = ${JSON.stringify(map, null, 2)};\n`;
  writeFileSync(OUT, header);
}

// ---------- prompt + parse (shared by both providers) ----------
function buildPrompt(d) {
  return `Analyze this menu item: "${d.name}"${d.category ? ` (category: ${d.category})` : ''}${d.description ? ` — ${d.description}` : ''}.
Give exactly 3 primary flavor/sensory notes with a percentage each (must total 100). Also a vivid one-sentence tasting note (<22 words).
Return ONLY JSON: {"notes":[{"label":"string (1-2 words)","percentage":number}],"tastingNote":"string"}`;
}
function parseProfile(text) {
  const m = text && text.match(/\{[\s\S]*\}/);
  if (!m) return null;
  let parsed;
  try { parsed = JSON.parse(m[0]); } catch { return null; }
  if (!parsed || !Array.isArray(parsed.notes) || !parsed.notes.length) return null;
  return {
    notes: parsed.notes.slice(0, 3).map((n) => ({
      label: String(n.label ?? '').slice(0, 20),
      percentage: Math.max(0, Math.min(100, Math.round(Number(n.percentage) || 0))),
    })),
    tastingNote: String(parsed.tastingNote ?? ''),
  };
}
const is429 = (e) => e?.status === 429 || /429|quota|rate/i.test(e?.message || '');

// ---------- env / providers ----------
function readEnv(name) {
  let s = '';
  try { s = readFileSync(resolve(ROOT, '.env'), 'utf8'); } catch {}
  const m = s.match(new RegExp(`${name}=(.+)`));
  return m ? m[1].trim().replace(/^["']|["']$/g, '') : '';
}

async function makeGemini() {
  const key = readEnv('VITE_GEMINI_API_KEY');
  if (!key) return null;
  const { GoogleGenerativeAI } = await import(resolve(ROOT, 'node_modules/@google/generative-ai/dist/index.mjs'));
  const model = new GoogleGenerativeAI(key).getGenerativeModel({ model: 'gemini-2.5-flash' });
  return async (d) => {
    const r = await model.generateContent(buildPrompt(d));
    return parseProfile((await r.response).text());
  };
}

async function makeClaude() {
  const key = readEnv('ANTHROPIC_API_KEY') || process.env.ANTHROPIC_API_KEY;
  if (!key) return null;
  const { default: Anthropic } = await import(resolve(ROOT, 'node_modules/@anthropic-ai/sdk/index.mjs'));
  const client = new Anthropic({ apiKey: key });
  return async (d) => {
    const msg = await client.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 1024,
      messages: [{ role: 'user', content: buildPrompt(d) }],
    });
    const text = msg.content.filter((b) => b.type === 'text').map((b) => b.text).join('');
    return parseProfile(text);
  };
}

// ---------- one worker: pulls from the shared queue until empty ----------
async function worker(label, gen, spacingMs, queue, out, stats) {
  while (queue.length) {
    const d = queue.shift();
    if (!d || out[d.id]) continue;
    let ok = false;
    for (let attempt = 0; attempt < 4 && !ok; attempt++) {
      try {
        const profile = await gen(d);
        if (profile) {
          out[d.id] = profile;
          writeOut(out);
          ok = true;
          stats.done++;
          console.log(`✅ [${label}] ${Object.keys(out).length}/${stats.total} ${d.id} — ${profile.notes.map((n) => n.label).join(', ')}`);
        } else { throw new Error('bad shape'); }
      } catch (e) {
        if (is429(e)) {
          const wait = Math.min(70000, Math.round((parseFloat((e.message || '').match(/retry in ([\d.]+)s/i)?.[1]) * 1000) || 0) || 14000 * Math.pow(1.4, attempt));
          console.log(`   ⏳ [${label}] rate cap on ${d.id}, waiting ${Math.round(wait / 1000)}s`);
          await sleep(wait);
          attempt--; stats.cap++;
          if (stats.cap > 40) { console.log(`\n🛑 [${label}] sustained quota wall — worker stopping.`); return; }
        } else {
          console.log(`   ⚠️ [${label}] ${d.id} attempt ${attempt + 1}: ${(e.message || '').slice(0, 60)}`);
          await sleep(2500);
        }
      }
    }
    if (!ok) stats.failed++;
    await sleep(spacingMs);
  }
}

async function main() {
  const dishes = await allDishes();
  console.log(`Found ${dishes.length} dishes (${dishes.filter((d) => d.arEnabled).length} AR-enabled).`);
  if (COUNT_ONLY) return;

  const out = loadExisting();
  const queue = dishes.filter((d) => !out[d.id]);
  const stats = { total: dishes.length, done: 0, failed: 0, cap: 0 };

  const gemini = await makeGemini();
  const claude = await makeClaude();
  console.log(`Providers: ${[gemini && 'Gemini(2.5-flash)', claude && 'Claude(sonnet-4-6)'].filter(Boolean).join(' + ') || 'NONE'}`);
  console.log(`Already baked ${Object.keys(out).length}. ${queue.length} to go.\n`);
  if (!gemini && !claude) throw new Error('No provider key found (need VITE_GEMINI_API_KEY and/or ANTHROPIC_API_KEY in .env)');

  const workers = [];
  if (gemini) workers.push(worker('gemini', gemini, 13000, queue, out, stats)); // 5 RPM free tier
  if (claude) workers.push(worker('claude', claude, 2500, queue, out, stats));  // Sonnet has generous limits
  await Promise.all(workers);

  writeOut(out);
  console.log(`\nDone. Total baked: ${Object.keys(out).length}/${stats.total}. This run +${stats.done}, failed ${stats.failed}.`);
}

main().catch((e) => { console.error(e); process.exit(1); });
